# Loding Data Set

In [1]:
from sklearn import datasets

# 1st way

In [2]:
dataset_wine = datasets.load_wine()

In [3]:
print(dataset_wine)

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
 

In [4]:
dataset_iris = datasets.load_iris()

In [5]:
print(dataset_iris)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [6]:
# printing all data points against indicator variables

print(dataset_wine.data)

# printing all data points against predictive  variable

print(dataset_wine.target)

[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [7]:
print("size of dataset")
print(dataset_wine.data.shape)



size of dataset
(178, 13)


In [8]:
print("the sizz of the target feature")
print(dataset_wine.target.shape)

the sizz of the target feature
(178,)


In [9]:
print("The name of features as as below")
print(dataset_wine.feature_names)

The name of features as as below
['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']


In [10]:
print("The name of classes in target feature")
print(dataset_wine.target_names)

The name of classes in target feature
['class_0' 'class_1' 'class_2']


In [11]:
print("The sample data of first 5 data points is as below")
print(dataset_wine.data[0:5])

The sample data of first 5 data points is as below
[[1.423e+01 1.710e+00 2.430e+00 1.560e+01 1.270e+02 2.800e+00 3.060e+00
  2.800e-01 2.290e+00 5.640e+00 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 1.120e+01 1.000e+02 2.650e+00 2.760e+00
  2.600e-01 1.280e+00 4.380e+00 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 1.860e+01 1.010e+02 2.800e+00 3.240e+00
  3.000e-01 2.810e+00 5.680e+00 1.030e+00 3.170e+00 1.185e+03]
 [1.437e+01 1.950e+00 2.500e+00 1.680e+01 1.130e+02 3.850e+00 3.490e+00
  2.400e-01 2.180e+00 7.800e+00 8.600e-01 3.450e+00 1.480e+03]
 [1.324e+01 2.590e+00 2.870e+00 2.100e+01 1.180e+02 2.800e+00 2.690e+00
  3.900e-01 1.820e+00 4.320e+00 1.040e+00 2.930e+00 7.350e+02]]


In [12]:
print("The sample target values of first 5 data points is as below")
print(dataset_wine.target[0:5])

The sample target values of first 5 data points is as below
[0 0 0 0 0]


# 2. Loading User choice data set  in scikit learn

In [13]:
import pandas as pd

In [14]:
# Loading data set from local machine
My_dataset = pd.read_csv('C:/Users/Prince/Desktop/amity programing/CSV files/liver_dataset.csv')

In [15]:
My_dataset

mcv  alkphos  sgpt  sgot  gammagt  drink  target
0     85       92    45    27       31    0.0       1
1     85       64    59    32       23    0.0       2
2     86       54    33    16       54    0.0       2
3     91       78    34    24       36    0.0       2
4     87       70    12    28       10    0.0       2
..   ...      ...   ...   ...      ...    ...     ...
340   99       75    26    24       41   12.0       1
341   96       69    53    43      203   12.0       2
342   98       77    55    35       89   15.0       1
343   91       68    27    26       14   16.0       1
344   98       99    57    45       65   20.0       1

[345 rows x 7 columns]

In [16]:
My_dataset.head()

mcv  alkphos  sgpt  sgot  gammagt  drink  target
0   85       92    45    27       31    0.0       1
1   85       64    59    32       23    0.0       2
2   86       54    33    16       54    0.0       2
3   91       78    34    24       36    0.0       2
4   87       70    12    28       10    0.0       2

In [17]:
# Understanding data set
print("The size of the data set")
print(My_dataset.shape)
print("The data values of first 4 data points are as below(excluding target variable)")
print(My_dataset.iloc[0:4,0:6].values)
print("The class values of first 4 data points are as below")
print(My_dataset.iloc[0:4,6].values)

The size of the data set
(345, 7)
The data values of first 4 data points are as below(excluding target variable)
[[85. 92. 45. 27. 31.  0.]
 [85. 64. 59. 32. 23.  0.]
 [86. 54. 33. 16. 54.  0.]
 [91. 78. 34. 24. 36.  0.]]
The class values of first 4 data points are as below
[1 2 2 2]


# loding data set end

# Creating Hold-out enviornment for Model learning and testing

In Hold-out method we randomly divide data set into two parts.
Where the one part is used for learning the model and other for testing.
In practice, we usually take 70-30 proportion of data set for training and testing respectively.
Scikit learn provides inbuilt function that randomly divide data set into training and test data
samples based on the split entered by the user. Each training and test set should include 
information on indicator and predictor variables.





# Loading train_test_split library from scikit learn for Hold-Out enviornment

In [18]:
from sklearn.model_selection import train_test_split # using scikit learn for hold-out

# Creating Hold-out enviornment for sample data set in scikit learn

# 1. Loading data set

In [19]:
# Loading library
from sklearn import datasets

In [20]:
dataset_wine = datasets.load_wine()

In [21]:
print (dataset_wine)

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
 

# 2. Creating Hold-out enviornment for built in data set

In [52]:
winedata_train, winedata_test, winetarget_train, winetarget_test = train_test_split(dataset_wine.data, dataset_wine.target, test_size=0.3)

#The pair of arrays winedata_train and  winetarget_train will be used for learning
#the sueprvised model. 
#Whereas, winedata_test and  winetarget_test for model testing
print(winetarget_test)

[1 2 0 1 0 1 0 0 1 0 0 1 0 2 0 1 0 0 2 2 2 1 2 2 1 1 0 2 2 0 0 2 1 1 0 1 2
 2 1 0 0 1 1 1 1 1 2 0 2 0 1 2 2 2]


In [53]:
print(winedata_test)

[[1.182e+01 1.720e+00 1.880e+00 1.950e+01 8.600e+01 2.500e+00 1.640e+00
  3.700e-01 1.420e+00 2.060e+00 9.400e-01 2.440e+00 4.150e+02]
 [1.345e+01 3.700e+00 2.600e+00 2.300e+01 1.110e+02 1.700e+00 9.200e-01
  4.300e-01 1.460e+00 1.068e+01 8.500e-01 1.560e+00 6.950e+02]
 [1.406e+01 2.150e+00 2.610e+00 1.760e+01 1.210e+02 2.600e+00 2.510e+00
  3.100e-01 1.250e+00 5.050e+00 1.060e+00 3.580e+00 1.295e+03]
 [1.164e+01 2.060e+00 2.460e+00 2.160e+01 8.400e+01 1.950e+00 1.690e+00
  4.800e-01 1.350e+00 2.800e+00 1.000e+00 2.750e+00 6.800e+02]
 [1.356e+01 1.730e+00 2.460e+00 2.050e+01 1.160e+02 2.960e+00 2.780e+00
  2.000e-01 2.450e+00 6.250e+00 9.800e-01 3.030e+00 1.120e+03]
 [1.200e+01 9.200e-01 2.000e+00 1.900e+01 8.600e+01 2.420e+00 2.260e+00
  3.000e-01 1.430e+00 2.500e+00 1.380e+00 3.120e+00 2.780e+02]
 [1.377e+01 1.900e+00 2.680e+00 1.710e+01 1.150e+02 3.000e+00 2.790e+00
  3.900e-01 1.680e+00 6.300e+00 1.130e+00 2.930e+00 1.375e+03]
 [1.483e+01 1.640e+00 2.170e+00 1.400e+01 9.700e+01 2.8

In [54]:
print(winedata_train)

[[1.236e+01 3.830e+00 2.380e+00 ... 5.600e-01 1.580e+00 5.200e+02]
 [1.208e+01 1.390e+00 2.500e+00 ... 9.300e-01 3.190e+00 3.850e+02]
 [1.340e+01 4.600e+00 2.860e+00 ... 6.700e-01 1.920e+00 6.300e+02]
 ...
 [1.390e+01 1.680e+00 2.120e+00 ... 9.100e-01 3.330e+00 9.850e+02]
 [1.234e+01 2.450e+00 2.460e+00 ... 8.000e-01 3.380e+00 4.380e+02]
 [1.358e+01 1.660e+00 2.360e+00 ... 1.090e+00 2.880e+00 1.515e+03]]


In [55]:
print(winetarget_train)

[2 1 2 1 1 0 2 2 0 1 2 1 0 0 1 0 1 2 0 2 1 0 1 1 1 0 1 1 2 1 0 1 2 2 0 0 0
 1 2 1 1 0 0 1 1 2 2 0 2 0 2 1 0 0 2 2 0 1 0 2 2 1 0 1 1 1 0 1 1 1 2 1 0 0
 1 1 2 2 1 0 0 0 1 1 0 1 1 1 1 2 0 0 0 0 2 2 1 1 0 1 1 2 1 2 1 2 1 1 0 1 2
 0 0 2 1 0 2 1 1 0 0 0 1 0]


# Creating Hold-out enviornment for user defined data set

# 1. Import pandas

In [56]:
import pandas as pd
import numpy as np

# 2. Load user specific data set

In [57]:
# Loading data set from local machine. The data set on predicting liver disorder.
My_dataset.head()

mcv  alkphos  sgpt  sgot  gammagt  drink  target
0   85       92    45    27       31    0.0       1
1   85       64    59    32       23    0.0       2
2   86       54    33    16       54    0.0       2
3   91       78    34    24       36    0.0       2
4   87       70    12    28       10    0.0       2

In [58]:
My_dataset

mcv  alkphos  sgpt  sgot  gammagt  drink  target
0     85       92    45    27       31    0.0       1
1     85       64    59    32       23    0.0       2
2     86       54    33    16       54    0.0       2
3     91       78    34    24       36    0.0       2
4     87       70    12    28       10    0.0       2
..   ...      ...   ...   ...      ...    ...     ...
340   99       75    26    24       41   12.0       1
341   96       69    53    43      203   12.0       2
342   98       77    55    35       89   15.0       1
343   91       68    27    26       14   16.0       1
344   98       99    57    45       65   20.0       1

[345 rows x 7 columns]

In [59]:
My_dataset.head()

mcv  alkphos  sgpt  sgot  gammagt  drink  target
0   85       92    45    27       31    0.0       1
1   85       64    59    32       23    0.0       2
2   86       54    33    16       54    0.0       2
3   91       78    34    24       36    0.0       2
4   87       70    12    28       10    0.0       2

# 3. Creating Hold-out enviornment for user specific data set

In [60]:
# My_data contains all data points from My_data set from from first feature to  6th feature(indicator features)
My_data = My_dataset.iloc[:,0:6].values
print(My_data)

# My_target contains class information which is 7th feature in the data set of all the data points in My_dataset

My_target=My_dataset.iloc[:,6].values 
print(My_target)

[[85. 92. 45. 27. 31.  0.]
 [85. 64. 59. 32. 23.  0.]
 [86. 54. 33. 16. 54.  0.]
 ...
 [98. 77. 55. 35. 89. 15.]
 [91. 68. 27. 26. 14. 16.]
 [98. 99. 57. 45. 65. 20.]]
[1 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 1 2 2 2 2 1 1 1 1
 1 1 2 2 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 2 2 2 2 2 2 1 1 1 1 1 1 1 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 1 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1
 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 1 2 1 1 1 1 1 1 1 2 2 2 2 2 1 1 2 2
 2 2 2 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 2 2 2 2 2 1 1 1 1 1
 1 1 1 1 2 2 2 2 2 2 2 2 1 1 1 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 1 1 1 1 1 2 2 2 2
 2 1 1 2 2 2 2 1 2 1 1 1]


In [61]:
#  The pair of arrays liverdata_train and  livertarget_train will be used for learning the sueprvised model. 
# Whereas, liverdata_test and  livertarget_test for model testing

liverdata_train, liverdata_test, livertarget_train, livertarget_test = train_test_split(My_data, My_target, test_size=0.3)



In [62]:
print(liverdata_test)

[[ 97.   71.   29.   22.   52.    8. ]
 [ 89.   79.   17.   17.   16.    0.5]
 [ 92.   60.   23.   15.   19.    1. ]
 [ 97.   94.   43.   43.   82.    6. ]
 [ 98.   43.   35.   23.   69.    6. ]
 [ 91.  138.   45.   21.   48.   10. ]
 [ 92.   77.   86.   41.   31.   10. ]
 [ 88.   46.   29.   22.   18.    0.5]
 [ 65.   63.   19.   20.   14.    0.5]
 [ 90.   67.   10.   16.   16.    4. ]
 [ 86.   77.   25.   19.   18.    0.5]
 [ 85.   58.   83.   49.   51.    3. ]
 [ 88.   37.    9.   15.   16.    6. ]
 [ 92.   87.   57.   25.   44.    6. ]
 [ 90.   74.   19.   14.   22.    4. ]
 [ 82.   55.   18.   23.   44.    8. ]
 [ 84.   88.   28.   25.   35.    0.5]
 [ 89.   63.   24.   29.   29.    6. ]
 [ 98.   57.   31.   34.   73.   10. ]
 [ 88.   69.   70.   24.   64.    2. ]
 [ 92.  108.   53.   33.   94.   12. ]
 [ 98.   58.   33.   21.   28.    2. ]
 [ 88.   67.   21.   11.   11.    0.5]
 [ 90.   52.   10.   17.   12.    5. ]
 [ 90.   57.   31.   18.   37.    4. ]
 [ 90.   63.   45.   24. 

In [63]:
print(livertarget_test)

[1 1 1 1 2 1 1 2 2 2 1 2 2 2 2 2 2 2 2 1 2 1 1 2 2 2 2 2 1 2 1 2 1 1 2 1 1
 2 1 1 2 1 2 1 2 1 1 2 1 1 2 2 2 2 1 1 1 2 2 2 2 2 1 2 2 1 1 1 1 2 1 2 2 2
 2 2 1 2 1 1 2 2 1 2 2 1 1 2 1 1 1 1 2 2 2 1 2 2 2 2 2 2 2 2]


# Learning SVM training and Testing using Hold-Out method

# The code below demonstrates how SVM model is trained and tested under Hold-Out method. For better understanding, codes below explains building and testing SVM model on data set supported in scikit learn and user specific data set. 


# 1. Loading libraries

In [64]:
import pandas as pd
from sklearn import datasets # imports built in data sets supported in scikit learn 
from sklearn import svm #imports SVM classifier
from sklearn import metrics
from sklearn.model_selection import train_test_split # using scikit learn for hold-out

# loding data  set

In [65]:
#loding lod wine data set
dataset_wine = datasets.load_wine()

# Creating hold out inviornmen

In [66]:
winedata_train, winedata_test, winetarget_train, winetarget_test = train_test_split(dataset_wine.data, dataset_wine.target, test_size=0.3)


#The pair of arrays winedata_train and  winetarget_train will be used for learning
#the sueprvised model. 
#Whereas, winedata_test and  winetarget_test for model testing

# 4.  Building SVM model 

We will use training data set created in step 3 for model training(or learning). The supervised model we will be building now is Support Vector Machines(SVM). SVM by theory supports different types of kernels such as, linear, polynomial and radial basis. Where linear kernel is suitable for linearly separable problems whereas, other for non-linearly separable problems. For building SVM model, we try with different types of kernel to discover best kernel for given problem based on performance of model on unknown observation. 

In [67]:
#Create a svm Classifier. The various kernel supported in scikit learn are linear, poly and rbf.

SVMmodel_1 = svm.SVC(kernel='rbf') # Linear Kernel

#Train the model using the training sets

SVMfitted_1 = SVMmodel_1.fit(winedata_train, winetarget_train)

#  Testing trained SVM model on the test set 

In [68]:

#Predict the response on the test data set

SVM_predictions_1 = SVMfitted_1.predict((winedata_test))

# Evaluating the performance of the model 

In [69]:
# Computing Model Accuracy

print("Accuracy:",round(metrics.accuracy_score(winetarget_test, SVM_predictions_1),2) * 100, "%")

print ("---------------")

# Printing confusion matrix

print ("Confusion matrix")

print ("---------------")

print(metrics.confusion_matrix(winetarget_test, SVM_predictions_1))

# Model detailed classification report
target_names = ['class 0', 'class 1', 'class 2']


print ("---------------")

print("Classification report", metrics.classification_report(winetarget_test, SVM_predictions_1,target_names =target_names))

Accuracy: 76.0 %
---------------
Confusion matrix
---------------
[[17  0  2]
 [ 1 16  5]
 [ 1  4  8]]
---------------
Classification report               precision    recall  f1-score   support

     class 0       0.89      0.89      0.89        19
     class 1       0.80      0.73      0.76        22
     class 2       0.53      0.62      0.57        13

    accuracy                           0.76        54
   macro avg       0.74      0.75      0.74        54
weighted avg       0.77      0.76      0.76        54



# SVM on user specific data set

# 1. Loading data set

In [70]:
# Loading data set from local machine. The data set on predicting liver disorder.
    
My_dataset = pd.read_csv('C:/Users/Prince/Desktop/amity programing/CSV files/liver_dataset.csv')

In [71]:
My_dataset

mcv  alkphos  sgpt  sgot  gammagt  drink  target
0     85       92    45    27       31    0.0       1
1     85       64    59    32       23    0.0       2
2     86       54    33    16       54    0.0       2
3     91       78    34    24       36    0.0       2
4     87       70    12    28       10    0.0       2
..   ...      ...   ...   ...      ...    ...     ...
340   99       75    26    24       41   12.0       1
341   96       69    53    43      203   12.0       2
342   98       77    55    35       89   15.0       1
343   91       68    27    26       14   16.0       1
344   98       99    57    45       65   20.0       1

[345 rows x 7 columns]

# 2. Dividing data set into sets  of indicator and predictive variables

In [72]:
# My_data contains all data points from My_data set from from first feature to  6th feature(indicator features)
My_data = My_dataset.iloc[:,0:6].values 

# My_target contains class information which is 7th feature in the data set of all the data points in My_dataset

My_target=My_dataset.iloc[:,6].values 

print(My_data)
print(My_target)

[[85. 92. 45. 27. 31.  0.]
 [85. 64. 59. 32. 23.  0.]
 [86. 54. 33. 16. 54.  0.]
 ...
 [98. 77. 55. 35. 89. 15.]
 [91. 68. 27. 26. 14. 16.]
 [98. 99. 57. 45. 65. 20.]]
[1 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 1 2 2 2 2 1 1 1 1
 1 1 2 2 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 2 2 2 2 2 2 1 1 1 1 1 1 1 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 1 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1
 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 1 2 1 1 1 1 1 1 1 2 2 2 2 2 1 1 2 2
 2 2 2 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 2 2 2 2 2 1 1 1 1 1
 1 1 1 1 2 2 2 2 2 2 2 2 1 1 1 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 1 1 1 1 1 2 2 2 2
 2 1 1 2 2 2 2 1 2 1 1 1]


# 3. Creating Hold-out enviornment for the data set in step above

In [73]:
#  The pair of arrays liverdata_train and  livertarget_train will be used for learning the sueprvised model. 
# Whereas, liverdata_test and  livertarget_test for model testing

liverdata_train, liverdatatest, livertarget_train, livertarget_test = train_test_split(My_data, My_target, test_size=0.3)

In [74]:
print(liverdata_train)

[[84. 73. 46. 32. 39.  4.]
 [87. 59. 37. 27. 34.  2.]
 [91. 63. 17. 17. 46.  4.]
 ...
 [90. 63. 16. 21. 14.  1.]
 [88. 66. 23. 12. 15.  3.]
 [92. 65. 17. 25.  9.  2.]]


In [75]:
print(liverdata_test)

[[ 97.   71.   29.   22.   52.    8. ]
 [ 89.   79.   17.   17.   16.    0.5]
 [ 92.   60.   23.   15.   19.    1. ]
 [ 97.   94.   43.   43.   82.    6. ]
 [ 98.   43.   35.   23.   69.    6. ]
 [ 91.  138.   45.   21.   48.   10. ]
 [ 92.   77.   86.   41.   31.   10. ]
 [ 88.   46.   29.   22.   18.    0.5]
 [ 65.   63.   19.   20.   14.    0.5]
 [ 90.   67.   10.   16.   16.    4. ]
 [ 86.   77.   25.   19.   18.    0.5]
 [ 85.   58.   83.   49.   51.    3. ]
 [ 88.   37.    9.   15.   16.    6. ]
 [ 92.   87.   57.   25.   44.    6. ]
 [ 90.   74.   19.   14.   22.    4. ]
 [ 82.   55.   18.   23.   44.    8. ]
 [ 84.   88.   28.   25.   35.    0.5]
 [ 89.   63.   24.   29.   29.    6. ]
 [ 98.   57.   31.   34.   73.   10. ]
 [ 88.   69.   70.   24.   64.    2. ]
 [ 92.  108.   53.   33.   94.   12. ]
 [ 98.   58.   33.   21.   28.    2. ]
 [ 88.   67.   21.   11.   11.    0.5]
 [ 90.   52.   10.   17.   12.    5. ]
 [ 90.   57.   31.   18.   37.    4. ]
 [ 90.   63.   45.   24. 

In [76]:
print(livertarget_train)

[2 2 2 2 1 2 2 1 1 2 2 1 1 1 1 1 2 2 2 1 1 1 1 1 1 2 2 2 2 2 2 2 2 1 2 1 2
 1 1 2 2 2 1 2 2 2 1 1 1 2 2 2 1 1 1 2 2 1 1 1 2 2 2 2 2 1 2 2 2 1 2 1 1 2
 1 1 1 1 2 2 2 1 1 2 1 1 2 2 2 2 1 2 1 2 1 2 1 1 2 1 1 1 2 2 2 2 2 2 2 2 2
 1 1 2 2 2 2 2 2 1 2 2 1 2 2 2 2 2 2 2 1 1 1 2 1 1 2 2 2 2 1 2 2 1 1 1 1 1
 2 2 2 2 2 1 1 2 2 2 2 1 2 2 2 1 1 2 2 1 2 2 2 2 2 2 1 1 2 1 2 2 1 2 2 2 2
 2 2 1 1 1 2 2 2 1 2 1 2 1 1 1 2 2 2 2 2 1 2 2 2 1 1 2 1 1 2 1 1 2 2 2 1 2
 2 2 2 2 1 2 2 2 2 2 1 1 2 2 2 2 2 1 2]


In [77]:
print(livertarget_test)

[2 1 2 1 2 2 1 1 1 2 2 1 2 2 2 1 2 1 1 1 2 1 1 1 2 2 1 1 2 1 2 1 2 1 1 1 1
 2 2 2 1 1 1 2 1 2 2 2 1 1 1 1 2 2 2 2 1 1 1 1 2 1 1 2 1 2 2 2 1 1 2 2 2 1
 1 2 2 1 2 1 2 2 2 2 2 1 1 1 2 2 2 2 2 1 2 1 2 1 2 1 2 1 1 1]


In [78]:
#Create a svm Classifier. The various kernel supported in scikit learn are linear, poly and rbf.

SVMmodel_2 = svm.SVC(kernel='rbf') # Linear Kernel

#Train the model using the training sets

SVMfitted_2 = SVMmodel_2.fit(liverdata_train, livertarget_train)

# 5. Testing trained SVM model on the test set

In [79]:

#Predict the response on the test data set

SVM_predictions_2 = SVMfitted_2.predict((liverdata_test))

In [80]:
# Computing Model Accuracy

print("Accuracy:",round(metrics.accuracy_score(livertarget_test, SVM_predictions_2),2) * 100, "%")

print ("---------------")

# Printing confusion matrix


print ("Confusion matrix")

print ("---------------")
print(metrics.confusion_matrix(livertarget_test, SVM_predictions_2))


# User specific target names   
    
target_names = ['disorder', 'nodisorder']

# Model detailed classification report

print ("---------------")
print("Classification report", metrics.classification_report(livertarget_test, SVM_predictions_2,target_names =target_names))

Accuracy: 55.00000000000001 %
---------------
Confusion matrix
---------------
[[11 41]
 [ 6 46]]
---------------
Classification report               precision    recall  f1-score   support

    disorder       0.65      0.21      0.32        52
  nodisorder       0.53      0.88      0.66        52

    accuracy                           0.55       104
   macro avg       0.59      0.55      0.49       104
weighted avg       0.59      0.55      0.49       104



# Learning Decision tree training and Testing using Hold-Out method

# The code below demonstrates how Decision tree model is trained and tested under Hold-Out method. For better understanding, codes below explains building and testing Decision tree model on data set supported in scikit learn and user specific data set. 


# 1. Loading libraries

In [81]:
import pandas as pd # imports pandas for data structure support
from sklearn import datasets # imports built in data sets supported in scikit learn 
from sklearn import tree   # imports Decision tree classifier
from sklearn import metrics # imports performance metrices
from sklearn.model_selection import train_test_split # using scikit learn for hold-out

# 2. Loading data set

In [82]:
# Loading load_wine() data set 

dataset_wine = datasets.load_wine()



# 3. Creating Hold-out Enviornment

In [83]:
winedata_train, winedata_test, winetarget_train, winetarget_test = train_test_split(dataset_wine.data, dataset_wine.target, test_size=0.2)

In [84]:
print(winedata_train)

[[1.336e+01 2.560e+00 2.350e+00 ... 7.000e-01 2.470e+00 7.800e+02]
 [1.299e+01 1.670e+00 2.600e+00 ... 1.310e+00 3.500e+00 9.850e+02]
 [1.307e+01 1.500e+00 2.100e+00 ... 1.180e+00 2.690e+00 1.020e+03]
 ...
 [1.182e+01 1.720e+00 1.880e+00 ... 9.400e-01 2.440e+00 4.150e+02]
 [1.251e+01 1.730e+00 1.980e+00 ... 1.040e+00 3.570e+00 6.720e+02]
 [1.182e+01 1.470e+00 1.990e+00 ... 9.500e-01 3.330e+00 4.950e+02]]


In [85]:
print(winedata_test)

[[1.340e+01 3.910e+00 2.480e+00 2.300e+01 1.020e+02 1.800e+00 7.500e-01
  4.300e-01 1.410e+00 7.300e+00 7.000e-01 1.560e+00 7.500e+02]
 [1.329e+01 1.970e+00 2.680e+00 1.680e+01 1.020e+02 3.000e+00 3.230e+00
  3.100e-01 1.660e+00 6.000e+00 1.070e+00 2.840e+00 1.270e+03]
 [1.270e+01 3.550e+00 2.360e+00 2.150e+01 1.060e+02 1.700e+00 1.200e+00
  1.700e-01 8.400e-01 5.000e+00 7.800e-01 1.290e+00 6.000e+02]
 [1.237e+01 1.630e+00 2.300e+00 2.450e+01 8.800e+01 2.220e+00 2.450e+00
  4.000e-01 1.900e+00 2.120e+00 8.900e-01 2.780e+00 3.420e+02]
 [1.311e+01 1.010e+00 1.700e+00 1.500e+01 7.800e+01 2.980e+00 3.180e+00
  2.600e-01 2.280e+00 5.300e+00 1.120e+00 3.180e+00 5.020e+02]
 [1.327e+01 4.280e+00 2.260e+00 2.000e+01 1.200e+02 1.590e+00 6.900e-01
  4.300e-01 1.350e+00 1.020e+01 5.900e-01 1.560e+00 8.350e+02]
 [1.225e+01 1.730e+00 2.120e+00 1.900e+01 8.000e+01 1.650e+00 2.030e+00
  3.700e-01 1.630e+00 3.400e+00 1.000e+00 3.170e+00 5.100e+02]
 [1.208e+01 1.130e+00 2.510e+00 2.400e+01 7.800e+01 2.0

In [86]:
print(winetarget_train)

[2 1 0 1 0 0 2 0 1 2 2 1 0 0 1 0 1 2 2 1 0 1 1 2 1 1 2 0 1 1 2 0 0 2 0 2 1
 1 1 2 0 0 1 1 0 0 0 1 1 2 1 0 0 0 0 0 1 2 0 2 0 1 0 2 0 1 0 2 1 1 1 1 2 2
 0 2 2 0 2 2 0 0 2 0 1 0 0 1 1 0 1 2 1 0 2 0 1 1 1 0 1 1 0 1 1 1 1 0 0 2 2
 0 0 1 2 2 2 1 1 0 1 1 2 2 1 0 1 2 2 2 2 0 0 2 0 1 2 2 2 1 1 1]


In [87]:
print(winetarget_test)

[2 0 2 1 1 2 1 1 2 1 0 1 0 1 2 0 2 1 1 1 0 0 1 2 1 0 1 0 0 0 1 1 1 0 1 1]


# 4.  Building Decision tree model 

We will use training data set created in step 3 for model training(or learning)

In [89]:
#Create a Decision tree Classifier

DTmodel_1 = tree.DecisionTreeClassifier() 

#Train the model using the training sets

DTfitted_1 = DTmodel_1.fit(winedata_train, winetarget_train)

# 5. Testing trained Decision tree model on the test set 

In [90]:

#Predict the response on the test data set

DT_predictions_1 = DTfitted_1.predict((winedata_test))

# 6. Evaluating the performance of the model 

In [91]:
# Computing Model Accuracy

print("Accuracy:",round(metrics.accuracy_score(winetarget_test, DT_predictions_1),2) * 100, "%")

print ("---------------")

# Printing confusion matrix

print ("Confusion matrix")

print ("---------------")

print(metrics.confusion_matrix(winetarget_test, DT_predictions_1))

# Model detailed classification report
target_names = ['class 0', 'class 1', 'class 2']


print ("---------------")

print("Classification report", metrics.classification_report(winetarget_test, DT_predictions_1,target_names =target_names))

Accuracy: 92.0 %
---------------
Confusion matrix
---------------
[[10  1  0]
 [ 1 16  1]
 [ 0  0  7]]
---------------
Classification report               precision    recall  f1-score   support

     class 0       0.91      0.91      0.91        11
     class 1       0.94      0.89      0.91        18
     class 2       0.88      1.00      0.93         7

    accuracy                           0.92        36
   macro avg       0.91      0.93      0.92        36
weighted avg       0.92      0.92      0.92        36



# Decision Tree on user specific data set

# 1. Loading data set

In [92]:
# Loading data set from local machine. The data set on predicting liver disorder.
    
My_dataset = pd.read_csv('C:/Users/Prince/Desktop/amity programing/CSV files/liver_dataset.csv')
print(My_dataset)

     mcv  alkphos  sgpt  sgot  gammagt  drink  target
0     85       92    45    27       31    0.0       1
1     85       64    59    32       23    0.0       2
2     86       54    33    16       54    0.0       2
3     91       78    34    24       36    0.0       2
4     87       70    12    28       10    0.0       2
..   ...      ...   ...   ...      ...    ...     ...
340   99       75    26    24       41   12.0       1
341   96       69    53    43      203   12.0       2
342   98       77    55    35       89   15.0       1
343   91       68    27    26       14   16.0       1
344   98       99    57    45       65   20.0       1

[345 rows x 7 columns]


# 2. Dividing data set into sets  of indicator and predictive variables

In [93]:
# My_data contains all data points from My_data set from from first feature to  6th feature(indicator features)
My_data = My_dataset.iloc[:,0:6].values 

# My_target contains class information which is 7th feature in the data set of all the data points in My_dataset

My_target=My_dataset.iloc[:,6].values 

# 3. Creating Hold-out enviornment for the data set in step above

In [94]:
#  The pair of arrays liverdata_train and  livertarget_train will be used for learning the sueprvised model. 
# Whereas, liverdata_test and  livertarget_test for model testing

liverdata_train, liverdata_test, livertarget_train, livertarget_test = train_test_split(My_data, My_target, test_size=0.3)



# 4.  Building Decision tree model

In [95]:

DTmodel_2 = tree.DecisionTreeClassifier()  

#Train the model using the training sets

DTfitted_2 = DTmodel_2.fit(liverdata_train, livertarget_train)

# 5. Testing trained Decision tree model on the test set

In [96]:

#Predict the response on the test data set

DT_predictions_2 = DTfitted_2.predict((liverdata_test))

# 6. Evaluating the performance of the model

In [97]:
# Computing Model Accuracy

print("Accuracy:",round(metrics.accuracy_score(livertarget_test, DT_predictions_2),2) * 100, "%")

print ("---------------")

# Printing confusion matrix


print ("Confusion matrix")

print ("---------------")
print(metrics.confusion_matrix(livertarget_test, DT_predictions_2))


# User specific target names   
    
target_names = ['disorder', 'nodisorder']

# Model detailed classification report

print ("---------------")
print("Classification report", metrics.classification_report(livertarget_test, DT_predictions_2,target_names =target_names))

Accuracy: 71.0 %
---------------
Confusion matrix
---------------
[[31 15]
 [15 43]]
---------------
Classification report               precision    recall  f1-score   support

    disorder       0.67      0.67      0.67        46
  nodisorder       0.74      0.74      0.74        58

    accuracy                           0.71       104
   macro avg       0.71      0.71      0.71       104
weighted avg       0.71      0.71      0.71       104



# Visualize Decision tree model

In [98]:
# importing libraries

from IPython.display import Image  
import pydotplus

ModuleNotFoundError: No module named 'pydotplus'

In [99]:
# Create DOT data. The first argument in tree.export_graphviz is the model name, out_file is used to write 
# model into out_file, next parameters are information on indicator and predictive parameters 

dot_data = tree.export_graphviz(DTmodel_1, out_file=None, feature_names=dataset_wine.feature_names, class_names=dataset_wine.target_names)

# Draw graph

graph = pydotplus.graph_from_dot_data(dot_data)  

# Show graph
Image(graph.create_png())

NameError: name 'pydotplus' is not defined

# Learning KNN training and Testing using Hold-Out method

# The code below demonstrates how KNN model is trained and tested under Hold-Out method. For better understanding, codes below explains building and testing KNN model on data set supported in scikit learn and user specific data set. 


# 1. Loading libraries

In [103]:
import pandas as pd
from sklearn import datasets # imports built in data sets supported in scikit learn 
from sklearn.neighbors import KNeighborsClassifier  # imports KNN classifier
from sklearn import metrics
from sklearn.model_selection import train_test_split # using scikit learn for hold-out

# 2. Loading data set

In [104]:
# Loading load_wine() data set 

dataset_wine = datasets.load_wine()



In [107]:
dataset_wine

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

# 3. Creating Hold-out Enviornment

In [108]:
winedata_train, winedata_test, winetarget_train, winetarget_test = train_test_split(dataset_wine.data, dataset_wine.target, test_size=0.3)

In [110]:
print(winedata_train)

[[1.237e+01 1.630e+00 2.300e+00 ... 8.900e-01 2.780e+00 3.420e+02]
 [1.165e+01 1.670e+00 2.620e+00 ... 1.360e+00 3.210e+00 5.620e+02]
 [1.156e+01 2.050e+00 3.230e+00 ... 9.300e-01 3.690e+00 4.650e+02]
 ...
 [1.356e+01 1.730e+00 2.460e+00 ... 9.800e-01 3.030e+00 1.120e+03]
 [1.375e+01 1.730e+00 2.410e+00 ... 1.150e+00 2.900e+00 1.320e+03]
 [1.187e+01 4.310e+00 2.390e+00 ... 7.500e-01 3.640e+00 3.800e+02]]


In [111]:
print(winedata_test)

[[1.243e+01 1.530e+00 2.290e+00 2.150e+01 8.600e+01 2.740e+00 3.150e+00
  3.900e-01 1.770e+00 3.940e+00 6.900e-01 2.840e+00 3.520e+02]
 [1.200e+01 3.430e+00 2.000e+00 1.900e+01 8.700e+01 2.000e+00 1.640e+00
  3.700e-01 1.870e+00 1.280e+00 9.300e-01 3.050e+00 5.640e+02]
 [1.200e+01 9.200e-01 2.000e+00 1.900e+01 8.600e+01 2.420e+00 2.260e+00
  3.000e-01 1.430e+00 2.500e+00 1.380e+00 3.120e+00 2.780e+02]
 [1.371e+01 5.650e+00 2.450e+00 2.050e+01 9.500e+01 1.680e+00 6.100e-01
  5.200e-01 1.060e+00 7.700e+00 6.400e-01 1.740e+00 7.400e+02]
 [1.305e+01 1.650e+00 2.550e+00 1.800e+01 9.800e+01 2.450e+00 2.430e+00
  2.900e-01 1.440e+00 4.250e+00 1.120e+00 2.510e+00 1.105e+03]
 [1.430e+01 1.920e+00 2.720e+00 2.000e+01 1.200e+02 2.800e+00 3.140e+00
  3.300e-01 1.970e+00 6.200e+00 1.070e+00 2.650e+00 1.280e+03]
 [1.386e+01 1.510e+00 2.670e+00 2.500e+01 8.600e+01 2.950e+00 2.860e+00
  2.100e-01 1.870e+00 3.380e+00 1.360e+00 3.160e+00 4.100e+02]
 [1.229e+01 1.610e+00 2.210e+00 2.040e+01 1.030e+02 1.1

In [112]:
print(winetarget_train)

[1 1 1 0 2 0 2 2 2 2 0 1 0 0 2 2 1 0 2 2 2 2 1 2 0 1 1 2 0 1 1 1 0 2 2 2 1
 0 0 1 0 0 1 1 1 2 1 2 2 1 2 2 0 1 1 0 0 1 2 1 0 2 1 2 0 0 1 2 1 2 1 1 1 1
 0 1 2 2 0 1 2 1 2 0 2 1 0 0 1 1 0 0 2 1 1 0 2 2 0 1 0 1 0 0 1 0 2 1 1 0 2
 2 1 0 2 2 1 1 0 0 0 0 0 1]


In [113]:
print(winetarget_test)

[1 1 1 2 0 0 1 1 1 1 2 0 2 1 1 2 2 0 1 0 2 2 1 2 1 0 0 0 1 2 1 0 1 0 1 0 1
 0 0 1 1 0 1 1 1 0 0 1 0 0 0 1 1 0]


# 4.  Building KNN model 

We will use training data set created in step 3 for model training(or learning). The supervised model we will be building now is KNN classifier. KNN classifier requires user to specify number of nearest neighbor to train the model.  Here, user can try different values of K to test the performance of the classifier. If user does not specify the value of K then, the model takes the default value of 5. 

In [116]:
#Create a KNN Classifier. The KNeighborsClassifier function takes value of k.
KNNnmodel_1 = KNeighborsClassifier(n_neighbors=4)

#Train the model using the training sets
KNNfitted_1 = KNNnmodel_1.fit(winedata_train, winetarget_train)

# 5. Testing trained KNN model on the test set 

In [117]:
#Predict the response on the test data set
KNN_predictions_1 = KNNfitted_1.predict((winedata_test))

# 6. Evaluating the performance of the model 

In [118]:
# Computing Model Accuracy

print("Accuracy:",round(metrics.accuracy_score(winetarget_test, KNN_predictions_1),2) * 100, "%")

print ("---------------")

# Printing confusion matrix

print ("Confusion matrix")

print ("---------------")

print(metrics.confusion_matrix(winetarget_test, KNN_predictions_1))

# Model detailed classification report
target_names = ['class 0', 'class 1', 'class 2']


print ("---------------")

print("Classification report", metrics.classification_report(winetarget_test, KNN_predictions_1,target_names =target_names))

Accuracy: 76.0 %
---------------
Confusion matrix
---------------
[[18  1  1]
 [ 2 20  3]
 [ 2  4  3]]
---------------
Classification report               precision    recall  f1-score   support

     class 0       0.82      0.90      0.86        20
     class 1       0.80      0.80      0.80        25
     class 2       0.43      0.33      0.38         9

    accuracy                           0.76        54
   macro avg       0.68      0.68      0.68        54
weighted avg       0.74      0.76      0.75        54



# KNN on user specific data set

# 1. Loading data set

In [119]:
# Loading data set from local machine
My_dataset = pd.read_csv('C:/Users/Prince/Desktop/amity programing/CSV files/liver_dataset.csv')

In [120]:
My_dataset.head()

mcv  alkphos  sgpt  sgot  gammagt  drink  target
0   85       92    45    27       31    0.0       1
1   85       64    59    32       23    0.0       2
2   86       54    33    16       54    0.0       2
3   91       78    34    24       36    0.0       2
4   87       70    12    28       10    0.0       2

# 2. Dividing data set into sets  of indicator and predictive variables

In [121]:
# My_data contains all data points from My_data set from from first feature to  6th feature(indicator features)
My_data = My_dataset.iloc[:,0:6].values

# My_target contains class information which is 7th feature in the data set of all the data points in My_dataset
My_target = My_dataset.iloc[:,6].values

# 3. Creating Hold-out enviornment for the data set in step above

In [122]:
#  The pair of arrays liverdata_train and  livertarget_train will be used for learning the sueprvised model. 
# Whereas, liverdata_test and  livertarget_test for model testing

liverdata_train, liverdata_test, livertarget_train, livertarget_test = train_test_split(My_data, My_target, test_size=0.3)

In [123]:
print(liverdata_train)

[[ 91.   60.   32.   14.    8.    1. ]
 [ 91.   63.   17.   17.   46.    4. ]
 [ 91.   96.   35.   22.  135.    0.5]
 ...
 [ 90.   62.   22.   21.   21.    8. ]
 [ 85.   62.   15.   13.   22.    0.5]
 [ 95.   50.   29.   25.   50.    0.5]]


In [124]:
print(liverdata_test)

[[ 83.   54.   27.   15.   12.    0.5]
 [ 98.   74.  148.   75.  159.    0.5]
 [ 89.   82.   33.   32.   18.    0.5]
 [ 89.   35.   27.   29.   17.    4. ]
 [ 95.   73.   20.   25.  225.    8. ]
 [ 96.   44.   42.   23.   73.    8. ]
 [ 90.   61.   28.   29.   31.    2. ]
 [ 85.  119.   30.   26.   17.    0.5]
 [ 95.   93.   21.   27.   47.    6. ]
 [ 92.   79.   22.   20.   11.    3. ]
 [ 86.  109.   16.   22.   28.    6. ]
 [ 91.   44.   18.   18.   23.    2. ]
 [ 87.   90.   43.   28.  156.    2. ]
 [ 84.   83.   20.   25.    7.    3. ]
 [ 83.   45.   19.   21.   13.    4. ]
 [ 94.   43.  154.   82.  121.    4. ]
 [ 90.   80.   19.   14.   42.    2. ]
 [ 91.   57.   31.   23.   42.    0.5]
 [ 92.   62.   37.   21.   36.    6. ]
 [ 96.   69.   53.   43.  203.   12. ]
 [ 82.   72.   31.   20.   84.    3. ]
 [ 93.   84.   58.   47.   62.    7. ]
 [ 79.  101.   17.   27.   23.    4. ]
 [ 91.   68.   14.   20.   19.    4. ]
 [ 97.   93.   21.   20.   68.    6. ]
 [ 85.   59.   25.   20. 

In [127]:
print(livertarget_train)

[1 2 1 2 1 1 2 2 2 2 2 2 1 2 2 2 1 1 2 2 1 2 1 1 1 2 2 2 1 2 1 1 1 2 1 2 2
 1 2 2 1 1 1 1 2 2 2 1 2 2 1 2 2 2 1 1 2 2 2 1 1 1 1 2 1 2 1 1 1 1 2 1 1 1
 2 1 1 2 2 2 1 2 1 1 1 2 1 1 2 1 1 2 1 2 2 2 2 1 2 2 2 1 1 1 2 2 1 1 2 1 2
 2 2 2 2 1 2 2 2 2 2 2 2 2 1 2 2 2 1 2 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 1 2 1 2 1 2 2 1 2 1 2 1 2 1 1 1 2 1 1 1 2 2 1 2 1 1 2 2 1 2 2 1 2
 2 1 1 1 2 2 2 2 2 1 2 2 1 2 2 1 2 2 2 2 1 2 2 2 1 2 2 1 2 1 1 2 1 1 2 1 1
 2 2 1 2 1 2 1 2 2 2 2 2 1 2 1 1 1 2 2]


In [128]:
print(livertarget_test)

[1 2 1 1 2 1 1 1 2 1 2 2 2 1 2 2 1 1 1 2 2 2 2 2 2 2 2 2 1 2 2 1 2 2 2 1 1
 2 1 2 1 2 2 1 1 1 1 1 2 2 2 1 1 2 2 2 2 1 2 2 1 1 2 2 2 2 1 1 1 1 2 2 1 1
 2 2 2 1 1 1 2 1 2 1 1 2 1 2 2 2 2 1 1 1 2 1 2 2 2 2 1 2 1 2]


# 4.  Building KNN model

In [129]:
#Create a KNN Classifier. The KNeighborsClassifier function takes value of k.
KNNnmodel_2 = KNeighborsClassifier(n_neighbors = 4)

#Train the model using the training sets
KNNfitted_2 = KNNnmodel_2.fit(liverdata_train, livertarget_train)



# 5. Testing trained KNN model on the test set

In [130]:
#Predict the response on the test data set
KNN_predictions_2 = KNNfitted_2.predict((liverdata_test))

# 6. Evaluating the performance of the model

In [131]:
# Computing Model Accuracy

print("Accuracy:",round(metrics.accuracy_score(livertarget_test, KNN_predictions_2),2) * 100, "%")

print ("---------------")

# Printing confusion matrix


print ("Confusion matrix")

print ("---------------")
print(metrics.confusion_matrix(livertarget_test, KNN_predictions_2))


# User specific target names   
    
target_names = ['disorder', 'nodisorder']

# Model detailed classification report

print ("---------------")
print("Classification report", metrics.classification_report(livertarget_test, KNN_predictions_2,target_names =target_names))

Accuracy: 62.0 %
---------------
Confusion matrix
---------------
[[28 18]
 [21 37]]
---------------
Classification report               precision    recall  f1-score   support

    disorder       0.57      0.61      0.59        46
  nodisorder       0.67      0.64      0.65        58

    accuracy                           0.62       104
   macro avg       0.62      0.62      0.62       104
weighted avg       0.63      0.62      0.63       104

